# Generated by Django 2.0.7 on 2018-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180813_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Misc.', max_length=80),
            preserve_default=False,
        ),
    ]
